name: manylangs
description: ManyLangs – AI Grammar • Conversation • Pronunciation • Composition
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core & auth/DB/functions
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3

  # 결제 페이지 오픈용
  url_launcher: ^6.3.0

  # (선택) 상태관리/유틸 필요시 여기에 추가
  # provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # 앱에서 사용할 정적 리소스가 있다면 assets 폴더 유지
  assets:
    - assets/

  # (선택) 커스텀 폰트를 쓰면 여기 선언
  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Regular.ttf
