// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwpdwH2G1fEYJpBU-aAKzxSrGYT5_m8yk',
    appId: '1:464004135729:web:3c6ffe259d3307a5018e10',
    messagingSenderId: '464004135729',
    projectId: 'manylangs-7299b',
    authDomain: 'manylangs-7299b.firebaseapp.com',
    storageBucket: 'manylangs-7299b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxCoD2AInDjM_vvmd4OX4llHsdj3wdrk',
    appId: '1:464004135729:android:5ce83d66a64dea4c018e10',
    messagingSenderId: '464004135729',
    projectId: 'manylangs-7299b',
    storageBucket: 'manylangs-7299b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANwPURBKMnB3JiJxO3lNpoBeFrEQGKhvs',
    appId: '1:464004135729:ios:0c7308cd8b5ee562018e10',
    messagingSenderId: '464004135729',
    projectId: 'manylangs-7299b',
    storageBucket: 'manylangs-7299b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANwPURBKMnB3JiJxO3lNpoBeFrEQGKhvs',
    appId: '1:464004135729:ios:0c7308cd8b5ee562018e10',
    messagingSenderId: '464004135729',
    projectId: 'manylangs-7299b',
    storageBucket: 'manylangs-7299b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwpdwH2G1fEYJpBU-aAKzxSrGYT5_m8yk',
    appId: '1:464004135729:web:d199df7d36415a62018e10',
    messagingSenderId: '464004135729',
    projectId: 'manylangs-7299b',
    authDomain: 'manylangs-7299b.firebaseapp.com',
    storageBucket: 'manylangs-7299b.firebasestorage.app',
  );
}
