export const EN_TERMS = [
  "Korean language school",
  "Korean school",
  "Korean academy",
  "Korean institute",
  "Korean language institute",
  "Korean language center",
  "Korean language centre",
  "Korean learning center",
  "Korean learning centre",
  "Korean education center",
  "Korean course",
  "Korean courses",
  "Korean classes",
  "Korean class",
  "Korean lessons",
  "Korean lesson",
  "Korean tutor",
  "Korean teacher",
  "private Korean tutor",
  "private Korean lessons",
  "learn Korean",
  "study Korean",
  "Korean conversation class",
  "Korean speaking class",
  "Korean for beginners",
  "Korean for kids",
  "Korean for children",
  "Korean for adults",
  "online Korean classes",
  "online Korean tutor",
  "Korean exam preparation",
  "Korean test preparation",
  "English language school",
  "English school",
  "English academy",
  "English institute",
  "English language institute",
  "English language center",
  "English language centre",
  "English learning center",
  "English learning centre",
  "English education center",
  "English course",
  "English courses",
  "English classes",
  "English class",
  "English lessons",
  "English lesson",
  "English tutor",
  "English teacher",
  "private English tutor",
  "private English lessons",
  "learn English",
  "study English",
  "English conversation class",
  "English speaking class",
  "English for beginners",
  "English for kids",
  "English for children",
  "English for adults",
  "online English classes",
  "online English tutor",
  "English exam preparation",
  "English test preparation",
  "Spanish language school",
  "Spanish school",
  "Spanish academy",
  "Spanish institute",
  "Spanish language institute",
  "Spanish language center",
  "Spanish language centre",
  "Spanish learning center",
  "Spanish learning centre",
  "Spanish education center",
  "Spanish course",
  "Spanish courses",
  "Spanish classes",
  "Spanish class",
  "Spanish lessons",
  "Spanish lesson",
  "Spanish tutor",
  "Spanish teacher",
  "private Spanish tutor",
  "private Spanish lessons",
  "learn Spanish",
  "study Spanish",
  "Spanish conversation class",
  "Spanish speaking class",
  "Spanish for beginners",
  "Spanish for kids",
  "Spanish for children",
  "Spanish for adults",
  "online Spanish classes",
  "online Spanish tutor",
  "Spanish exam preparation",
  "Spanish test preparation",
  "French language school",
  "French school",
  "French academy",
  "French institute",
  "French language institute",
  "French language center",
  "French language centre",
  "French learning center",
  "French learning centre",
  "French education center",
  "French course",
  "French courses",
  "French classes",
  "French class",
  "French lessons",
  "French lesson",
  "French tutor",
  "French teacher",
  "private French tutor",
  "private French lessons",
  "learn French",
  "study French",
  "French conversation class",
  "French speaking class",
  "French for beginners",
  "French for kids",
  "French for children",
  "French for adults",
  "online French classes",
  "online French tutor",
  "French exam preparation",
  "French test preparation",
  "Portuguese language school",
  "Portuguese school",
  "Portuguese academy",
  "Portuguese institute",
  "Portuguese language institute",
  "Portuguese language center",
  "Portuguese language centre",
  "Portuguese learning center",
  "Portuguese learning centre",
  "Portuguese education center",
  "Portuguese course",
  "Portuguese courses",
  "Portuguese classes",
  "Portuguese class",
  "Portuguese lessons",
  "Portuguese lesson",
  "Portuguese tutor",
  "Portuguese teacher",
  "private Portuguese tutor",
  "private Portuguese lessons",
  "learn Portuguese",
  "study Portuguese",
  "Portuguese conversation class",
  "Portuguese speaking class",
  "Portuguese for beginners",
  "Portuguese for kids",
  "Portuguese for children",
  "Portuguese for adults",
  "online Portuguese classes",
  "online Portuguese tutor",
  "Portuguese exam preparation",
  "Portuguese test preparation",
  "Japanese language school",
  "Japanese school",
  "Japanese academy",
  "Japanese institute",
  "Japanese language institute",
  "Japanese language center",
  "Japanese language centre",
  "Japanese learning center",
  "Japanese learning centre",
  "Japanese education center",
  "Japanese course",
  "Japanese courses",
  "Japanese classes",
  "Japanese class",
  "Japanese lessons",
  "Japanese lesson",
  "Japanese tutor",
  "Japanese teacher",
  "private Japanese tutor",
  "private Japanese lessons",
  "learn Japanese",
  "study Japanese",
  "Japanese conversation class",
  "Japanese speaking class",
  "Japanese for beginners",
  "Japanese for kids",
  "Japanese for children",
  "Japanese for adults",
  "online Japanese classes",
  "online Japanese tutor",
  "Japanese exam preparation",
  "Japanese test preparation",
  "Chinese language school",
  "Chinese school",
  "Chinese academy",
  "Chinese institute",
  "Chinese language institute",
  "Chinese language center",
  "Chinese language centre",
  "Chinese learning center",
  "Chinese learning centre",
  "Chinese education center",
  "Chinese course",
  "Chinese courses",
  "Chinese classes",
  "Chinese class",
  "Chinese lessons",
  "Chinese lesson",
  "Chinese tutor",
  "Chinese teacher",
  "private Chinese tutor",
  "private Chinese lessons",
  "learn Chinese",
  "study Chinese",
  "Chinese conversation class",
  "Chinese speaking class",
  "Chinese for beginners",
  "Chinese for kids",
  "Chinese for children",
  "Chinese for adults",
  "online Chinese classes",
  "online Chinese tutor",
  "Chinese exam preparation",
  "Chinese test preparation",
  "Mandarin language school",
  "Mandarin school",
  "Mandarin academy",
  "Mandarin institute",
  "Mandarin language institute",
  "Mandarin language center",
  "Mandarin language centre",
  "Mandarin learning center",
  "Mandarin learning centre",
  "Mandarin education center",
  "Mandarin course",
  "Mandarin courses",
  "Mandarin classes",
  "Mandarin class",
  "Mandarin lessons",
  "Mandarin lesson",
  "Mandarin tutor",
  "Mandarin teacher",
  "private Mandarin tutor",
  "private Mandarin lessons",
  "learn Mandarin",
  "study Mandarin",
  "Mandarin conversation class",
  "Mandarin speaking class",
  "Mandarin for beginners",
  "Mandarin for kids",
  "Mandarin for children",
  "Mandarin for adults",
  "online Mandarin classes",
  "online Mandarin tutor",
  "Mandarin exam preparation",
  "Mandarin test preparation",
  "German language school",
  "German school",
  "German academy",
  "German institute",
  "German language institute",
  "German language center",
  "German language centre",
  "German learning center",
  "German learning centre",
  "German education center",
  "German course",
  "German courses",
  "German classes",
  "German class",
  "German lessons",
  "German lesson",
  "German tutor",
  "German teacher",
  "private German tutor",
  "private German lessons",
  "learn German",
  "study German",
  "German conversation class",
  "German speaking class",
  "German for beginners",
  "German for kids",
  "German for children",
  "German for adults",
  "online German classes",
  "online German tutor",
  "German exam preparation",
  "German test preparation",
  "Italian language school",
  "Italian school",
  "Italian academy",
  "Italian institute",
  "Italian language institute",
  "Italian language center",
  "Italian language centre",
  "Italian learning center",
  "Italian learning centre",
  "Italian education center",
  "Italian course",
  "Italian courses",
  "Italian classes",
  "Italian class",
  "Italian lessons",
  "Italian lesson",
  "Italian tutor",
  "Italian teacher",
  "private Italian tutor",
  "private Italian lessons",
  "learn Italian",
  "study Italian",
  "Italian conversation class",
  "Italian speaking class",
  "Italian for beginners",
  "Italian for kids",
  "Italian for children",
  "Italian for adults",
  "online Italian classes",
  "online Italian tutor",
  "Italian exam preparation",
  "Italian test preparation",
  "Russian language school",
  "Russian school",
  "Russian academy",
  "Russian institute",
  "Russian language institute",
  "Russian language center",
  "Russian language centre",
  "Russian learning center",
  "Russian learning centre",
  "Russian education center",
  "Russian course",
  "Russian courses",
  "Russian classes",
  "Russian class",
  "Russian lessons",
  "Russian lesson",
  "Russian tutor",
  "Russian teacher",
  "private Russian tutor",
  "private Russian lessons",
  "learn Russian",
  "study Russian",
  "Russian conversation class",
  "Russian speaking class",
  "Russian for beginners",
  "Russian for kids",
  "Russian for children",
  "Russian for adults",
  "online Russian classes",
  "online Russian tutor",
  "Russian exam preparation",
  "Russian test preparation",
  "Arabic language school",
  "Arabic school",
  "Arabic academy",
  "Arabic institute",
  "Arabic language institute",
  "Arabic language center",
  "Arabic language centre",
  "Arabic learning center",
  "Arabic learning centre",
  "Arabic education center",
  "Arabic course",
  "Arabic courses",
  "Arabic classes",
  "Arabic class",
  "Arabic lessons",
  "Arabic lesson",
  "Arabic tutor",
  "Arabic teacher",
  "private Arabic tutor",
  "private Arabic lessons",
  "learn Arabic",
  "study Arabic",
  "Arabic conversation class",
  "Arabic speaking class",
  "Arabic for beginners",
  "Arabic for kids",
  "Arabic for children",
  "Arabic for adults",
  "online Arabic classes",
  "online Arabic tutor",
  "Arabic exam preparation",
  "Arabic test preparation",
  "Dutch language school",
  "Dutch school",
  "Dutch academy",
  "Dutch institute",
  "Dutch language institute",
  "Dutch language center",
  "Dutch language centre",
  "Dutch learning center",
  "Dutch learning centre",
  "Dutch education center",
  "Dutch course",
  "Dutch courses",
  "Dutch classes",
  "Dutch class",
  "Dutch lessons",
  "Dutch lesson",
  "Dutch tutor",
  "Dutch teacher",
  "language school",
  "language academy",
  "language institute",
  "language center",
  "language centre",
  "foreign language school",
  "foreign language academy",
  "foreign language institute",
  "language learning center",
  "language learning centre",
  "language education center",
  "language training center",
  "language training centre",
  "tutoring center",
  "tutoring centre",
  "learning center",
  "learning centre",
  "education center",
  "education centre",
  "academy",
  "institute",
  "training center",
  "training centre",
  "test preparation center",
  "test preparation centre",
  "exam preparation center",
  "IELTS course",
  "IELTS class",
  "IELTS preparation",
  "TOEFL course",
  "TOEFL class",
  "TOEFL preparation",
  "TOEIC course",
  "TOEIC preparation",
  "Cambridge English course",
  "Cambridge exam preparation",
  "TOPIK course",
  "TOPIK class",
  "TOPIK preparation",
  "TOPIK academy",
  "JLPT course",
  "JLPT preparation",
  "HSK course",
  "HSK preparation",
  "DELE course",
  "DELE preparation",
  "DELF course",
  "DALF course",
  "Goethe Zertifikat course",
  "language tutor",
  "foreign language tutor",
  "private language tutor",
  "language teacher",
  "foreign language teacher",
  "private language teacher",
  "foreign language lessons",
  "foreign language classes",
  "online language classes",
  "online language lessons",
  "online language tutor",
  "language school for adults",
  "language school for kids",
  "children's language school",
  "kids language academy",
  "bilingual school",
  "international school",
  "international language school",
  "study abroad agency",
  "study abroad consultant",
  "overseas education consultant",
  "student exchange agency",
  "au pair agency",
  "translation service",
  "translation agency",
  "interpretation service",
  "interpreter agency",
  "cultural center",
  "cultural centre",
  "cultural exchange center",
  "community college",
  "adult education center",
  "adult education centre",
  "continuing education center",
  "corporate language training",
  "business language training",
  "company language classes",
  "language services",
  "ESL school",
  "EFL school",
  "ESL center",
  "language immersion program",
  "conversation exchange center",
  "after school language academy",
  "weekend language school",
  "summer language program",
  "intensive language course",
  "language proficiency test center",
];