export const ES_TERMS = [
  "escuela de coreano",
  "academia de coreano",
  "instituto de coreano",
  "centro de coreano",
  "curso de coreano",
  "cursos de coreano",
  "clases de coreano",
  "clases particulares de coreano",
  "profesor de coreano",
  "profesor particular de coreano",
  "tutor de coreano",
  "aprender coreano",
  "estudiar coreano",
  "clases de conversación de coreano",
  "clases online de coreano",
  "clases de coreano en línea",
  "coreano para niños",
  "coreano para adultos",
  "preparación de examen de coreano",
  "escuela de inglés",
  "academia de inglés",
  "instituto de inglés",
  "centro de inglés",
  "curso de inglés",
  "cursos de inglés",
  "clases de inglés",
  "clases particulares de inglés",
  "profesor de inglés",
  "profesor particular de inglés",
  "tutor de inglés",
  "aprender inglés",
  "estudiar inglés",
  "clases de conversación de inglés",
  "clases online de inglés",
  "clases de inglés en línea",
  "inglés para niños",
  "inglés para adultos",
  "preparación de examen de inglés",
  "escuela de español",
  "academia de español",
  "instituto de español",
  "centro de español",
  "curso de español",
  "cursos de español",
  "clases de español",
  "clases particulares de español",
  "profesor de español",
  "profesor particular de español",
  "tutor de español",
  "aprender español",
  "estudiar español",
  "clases de conversación de español",
  "clases online de español",
  "clases de español en línea",
  "español para niños",
  "español para adultos",
  "preparación de examen de español",
  "escuela de francés",
  "academia de francés",
  "instituto de francés",
  "centro de francés",
  "curso de francés",
  "cursos de francés",
  "clases de francés",
  "clases particulares de francés",
  "profesor de francés",
  "profesor particular de francés",
  "tutor de francés",
  "aprender francés",
  "estudiar francés",
  "clases de conversación de francés",
  "clases online de francés",
  "clases de francés en línea",
  "francés para niños",
  "francés para adultos",
  "preparación de examen de francés",
  "escuela de portugués",
  "academia de portugués",
  "instituto de portugués",
  "centro de portugués",
  "curso de portugués",
  "cursos de portugués",
  "clases de portugués",
  "clases particulares de portugués",
  "profesor de portugués",
  "profesor particular de portugués",
  "tutor de portugués",
  "aprender portugués",
  "estudiar portugués",
  "clases de conversación de portugués",
  "clases online de portugués",
  "clases de portugués en línea",
  "portugués para niños",
  "portugués para adultos",
  "preparación de examen de portugués",
  "escuela de japonés",
  "academia de japonés",
  "instituto de japonés",
  "centro de japonés",
  "curso de japonés",
  "cursos de japonés",
  "clases de japonés",
  "clases particulares de japonés",
  "profesor de japonés",
  "profesor particular de japonés",
  "tutor de japonés",
  "aprender japonés",
  "estudiar japonés",
  "clases de conversación de japonés",
  "clases online de japonés",
  "clases de japonés en línea",
  "japonés para niños",
  "japonés para adultos",
  "preparación de examen de japonés",
  "escuela de chino",
  "academia de chino",
  "instituto de chino",
  "centro de chino",
  "curso de chino",
  "cursos de chino",
  "clases de chino",
  "clases particulares de chino",
  "profesor de chino",
  "profesor particular de chino",
  "tutor de chino",
  "aprender chino",
  "estudiar chino",
  "clases de conversación de chino",
  "clases online de chino",
  "clases de chino en línea",
  "chino para niños",
  "chino para adultos",
  "preparación de examen de chino",
  "escuela de mandarín",
  "academia de mandarín",
  "instituto de mandarín",
  "centro de mandarín",
  "curso de mandarín",
  "cursos de mandarín",
  "clases de mandarín",
  "clases particulares de mandarín",
  "profesor de mandarín",
  "profesor particular de mandarín",
  "tutor de mandarín",
  "aprender mandarín",
  "estudiar mandarín",
  "clases de conversación de mandarín",
  "clases online de mandarín",
  "clases de mandarín en línea",
  "mandarín para niños",
  "mandarín para adultos",
  "preparación de examen de mandarín",
  "escuela de alemán",
  "academia de alemán",
  "instituto de alemán",
  "centro de alemán",
  "curso de alemán",
  "cursos de alemán",
  "clases de alemán",
  "clases particulares de alemán",
  "profesor de alemán",
  "profesor particular de alemán",
  "tutor de alemán",
  "aprender alemán",
  "estudiar alemán",
  "clases de conversación de alemán",
  "clases online de alemán",
  "clases de alemán en línea",
  "alemán para niños",
  "alemán para adultos",
  "preparación de examen de alemán",
  "escuela de italiano",
  "academia de italiano",
  "instituto de italiano",
  "centro de italiano",
  "curso de italiano",
  "cursos de italiano",
  "clases de italiano",
  "clases particulares de italiano",
  "profesor de italiano",
  "profesor particular de italiano",
  "tutor de italiano",
  "aprender italiano",
  "estudiar italiano",
  "clases de conversación de italiano",
  "clases online de italiano",
  "clases de italiano en línea",
  "italiano para niños",
  "italiano para adultos",
  "preparación de examen de italiano",
  "escuela de ruso",
  "academia de ruso",
  "instituto de ruso",
  "centro de ruso",
  "curso de ruso",
  "cursos de ruso",
  "clases de ruso",
  "clases particulares de ruso",
  "profesor de ruso",
  "profesor particular de ruso",
  "tutor de ruso",
  "aprender ruso",
  "estudiar ruso",
  "clases de conversación de ruso",
  "clases online de ruso",
  "clases de ruso en línea",
  "ruso para niños",
  "ruso para adultos",
  "preparación de examen de ruso",
  "escuela de árabe",
  "academia de árabe",
  "instituto de árabe",
  "centro de árabe",
  "curso de árabe",
  "cursos de árabe",
  "clases de árabe",
  "clases particulares de árabe",
  "profesor de árabe",
  "profesor particular de árabe",
  "tutor de árabe",
  "aprender árabe",
  "estudiar árabe",
  "clases de conversación de árabe",
  "clases online de árabe",
  "clases de árabe en línea",
  "árabe para niños",
  "árabe para adultos",
  "preparación de examen de árabe",
  "escuela de neerlandés",
  "academia de neerlandés",
  "instituto de neerlandés",
  "centro de neerlandés",
  "curso de neerlandés",
  "cursos de neerlandés",
  "clases de neerlandés",
  "clases particulares de neerlandés",
  "profesor de neerlandés",
  "profesor particular de neerlandés",
  "tutor de neerlandés",
  "aprender neerlandés",
  "estudiar neerlandés",
  "clases de conversación de neerlandés",
  "clases online de neerlandés",
  "clases de neerlandés en línea",
  "neerlandés para niños",
  "neerlandés para adultos",
  "preparación de examen de neerlandés",
  "escuela de sueco",
  "academia de sueco",
  "instituto de sueco",
  "centro de sueco",
  "curso de sueco",
  "cursos de sueco",
  "clases de sueco",
  "clases particulares de sueco",
  "profesor de sueco",
  "profesor particular de sueco",
  "tutor de sueco",
  "aprender sueco",
  "estudiar sueco",
  "clases de conversación de sueco",
  "clases online de sueco",
  "clases de sueco en línea",
  "sueco para niños",
  "sueco para adultos",
  "preparación de examen de sueco",
  "escuela de turco",
  "academia de turco",
  "instituto de turco",
  "centro de turco",
  "curso de turco",
  "cursos de turco",
  "clases de turco",
  "clases particulares de turco",
  "profesor de turco",
  "profesor particular de turco",
  "tutor de turco",
  "aprender turco",
  "estudiar turco",
  "clases de conversación de turco",
  "clases online de turco",
  "clases de turco en línea",
  "turco para niños",
  "turco para adultos",
  "preparación de examen de turco",
  "escuela de polaco",
  "academia de polaco",
  "instituto de polaco",
  "centro de polaco",
  "curso de polaco",
  "cursos de polaco",
  "clases de polaco",
  "clases particulares de polaco",
  "profesor de polaco",
  "profesor particular de polaco",
  "tutor de polaco",
  "aprender polaco",
  "estudiar polaco",
  "clases de conversación de polaco",
  "clases online de polaco",
  "clases de polaco en línea",
  "polaco para niños",
  "polaco para adultos",
  "preparación de examen de polaco",
  "escuela de hindi",
  "academia de hindi",
  "instituto de hindi",
  "centro de hindi",
  "curso de hindi",
  "cursos de hindi",
  "clases de hindi",
  "clases particulares de hindi",
  "profesor de hindi",
  "profesor particular de hindi",
  "tutor de hindi",
  "aprender hindi",
  "estudiar hindi",
  "clases de conversación de hindi",
  "clases online de hindi",
  "clases de hindi en línea",
  "hindi para niños",
  "hindi para adultos",
  "preparación de examen de hindi",
  "escuela de vietnamita",
  "academia de vietnamita",
  "instituto de vietnamita",
  "centro de vietnamita",
  "curso de vietnamita",
  "cursos de vietnamita",
  "clases de vietnamita",
  "clases particulares de vietnamita",
  "profesor de vietnamita",
  "profesor particular de vietnamita",
  "tutor de vietnamita",
  "aprender vietnamita",
  "estudiar vietnamita",
  "clases de conversación de vietnamita",
  "clases online de vietnamita",
  "clases de vietnamita en línea",
  "vietnamita para niños",
  "vietnamita para adultos",
  "preparación de examen de vietnamita",
  "escuela de idiomas",
  "academia de idiomas",
  "instituto de idiomas",
  "centro de idiomas",
  "centro de formación",
  "centro de aprendizaje",
  "academia de lenguas",
  "escuela de lenguas",
  "escuela de idiomas extranjeros",
  "centro de educación",
  "academia",
  "instituto",
  "centro educativo",
  "centro de capacitación",
  "centro de tutoría",
  "clases particulares",
  "profesor particular",
  "escuela privada",
  "academia privada",
  "curso IELTS",
  "preparación IELTS",
  "curso TOEFL",
  "preparación TOEFL",
  "curso TOEIC",
  "preparación Cambridge",
  "curso TOPIK",
  "preparación TOPIK",
  "curso JLPT",
  "preparación JLPT",
  "curso HSK",
  "preparación HSK",
  "curso DELE",
  "preparación DELE",
  "curso DELF",
  "curso DALF",
  "curso Goethe Zertifikat",
  "preparación examen de alemán",
  "escuela bilingüe",
  "colegio internacional",
  "escuela internacional de idiomas",
  "agencia de intercambio estudiantil",
  "consultoría de estudios en el extranjero",
  "agencia de au pair",
  "servicio de traducción",
  "agencia de traducción",
  "servicio de interpretación",
  "agencia de intérpretes",
  "centro cultural",
  "centro de intercambio cultural",
  "educación para adultos",
  "centro de educación continua",
  "capacitación de idiomas para empresas",
  "clases de idiomas para empresas",
  "servicios lingüísticos",
  "escuela de idiomas para niños",
  "academia de idiomas infantil",
  "programa de inmersión lingüística",
  "centro de intercambio de conversación",
  "academia de idiomas de fin de semana",
  "curso intensivo de idiomas",
  "programa de idiomas de verano",
  "centro de certificación de idiomas",
];