export const FR_TERMS = [
  "école de coréen",
  "académie de coréen",
  "institut de coréen",
  "centre de coréen",
  "cours de coréen",
  "cours particuliers de coréen",
  "professeur de coréen",
  "professeur particulier de coréen",
  "tuteur de coréen",
  "apprendre le coréen",
  "étudier le coréen",
  "cours de conversation en coréen",
  "cours de coréen en ligne",
  "coréen pour enfants",
  "coréen pour adultes",
  "préparation examen de coréen",
  "école d'anglais",
  "académie d'anglais",
  "institut d'anglais",
  "centre d'anglais",
  "cours d'anglais",
  "cours particuliers d'anglais",
  "professeur d'anglais",
  "professeur particulier d'anglais",
  "tuteur d'anglais",
  "apprendre l'anglais",
  "étudier l'anglais",
  "cours de conversation en anglais",
  "cours d'anglais en ligne",
  "anglais pour enfants",
  "anglais pour adultes",
  "préparation examen d'anglais",
  "école d'espagnol",
  "académie d'espagnol",
  "institut d'espagnol",
  "centre d'espagnol",
  "cours d'espagnol",
  "cours particuliers d'espagnol",
  "professeur d'espagnol",
  "professeur particulier d'espagnol",
  "tuteur d'espagnol",
  "apprendre l'espagnol",
  "étudier l'espagnol",
  "cours de conversation en espagnol",
  "cours d'espagnol en ligne",
  "espagnol pour enfants",
  "espagnol pour adultes",
  "préparation examen d'espagnol",
  "école de français",
  "académie de français",
  "institut de français",
  "centre de français",
  "cours de français",
  "cours particuliers de français",
  "professeur de français",
  "professeur particulier de français",
  "tuteur de français",
  "apprendre le français",
  "étudier le français",
  "cours de conversation en français",
  "cours de français en ligne",
  "français pour enfants",
  "français pour adultes",
  "préparation examen de français",
  "école de portugais",
  "académie de portugais",
  "institut de portugais",
  "centre de portugais",
  "cours de portugais",
  "cours particuliers de portugais",
  "professeur de portugais",
  "professeur particulier de portugais",
  "tuteur de portugais",
  "apprendre le portugais",
  "étudier le portugais",
  "cours de conversation en portugais",
  "cours de portugais en ligne",
  "portugais pour enfants",
  "portugais pour adultes",
  "préparation examen de portugais",
  "école de japonais",
  "académie de japonais",
  "institut de japonais",
  "centre de japonais",
  "cours de japonais",
  "cours particuliers de japonais",
  "professeur de japonais",
  "professeur particulier de japonais",
  "tuteur de japonais",
  "apprendre le japonais",
  "étudier le japonais",
  "cours de conversation en japonais",
  "cours de japonais en ligne",
  "japonais pour enfants",
  "japonais pour adultes",
  "préparation examen de japonais",
  "école de chinois",
  "académie de chinois",
  "institut de chinois",
  "centre de chinois",
  "cours de chinois",
  "cours particuliers de chinois",
  "professeur de chinois",
  "professeur particulier de chinois",
  "tuteur de chinois",
  "apprendre le chinois",
  "étudier le chinois",
  "cours de conversation en chinois",
  "cours de chinois en ligne",
  "chinois pour enfants",
  "chinois pour adultes",
  "préparation examen de chinois",
  "école de mandarin",
  "académie de mandarin",
  "institut de mandarin",
  "centre de mandarin",
  "cours de mandarin",
  "cours particuliers de mandarin",
  "professeur de mandarin",
  "professeur particulier de mandarin",
  "tuteur de mandarin",
  "apprendre le mandarin",
  "étudier le mandarin",
  "cours de conversation en mandarin",
  "cours de mandarin en ligne",
  "mandarin pour enfants",
  "mandarin pour adultes",
  "préparation examen de mandarin",
  "école d'allemand",
  "académie d'allemand",
  "institut d'allemand",
  "centre d'allemand",
  "cours d'allemand",
  "cours particuliers d'allemand",
  "professeur d'allemand",
  "professeur particulier d'allemand",
  "tuteur d'allemand",
  "apprendre l'allemand",
  "étudier l'allemand",
  "cours de conversation en allemand",
  "cours d'allemand en ligne",
  "allemand pour enfants",
  "allemand pour adultes",
  "préparation examen d'allemand",
  "école d'italien",
  "académie d'italien",
  "institut d'italien",
  "centre d'italien",
  "cours d'italien",
  "cours particuliers d'italien",
  "professeur d'italien",
  "professeur particulier d'italien",
  "tuteur d'italien",
  "apprendre l'italien",
  "étudier l'italien",
  "cours de conversation en italien",
  "cours d'italien en ligne",
  "italien pour enfants",
  "italien pour adultes",
  "préparation examen d'italien",
  "école de russe",
  "académie de russe",
  "institut de russe",
  "centre de russe",
  "cours de russe",
  "cours particuliers de russe",
  "professeur de russe",
  "professeur particulier de russe",
  "tuteur de russe",
  "apprendre le russe",
  "étudier le russe",
  "cours de conversation en russe",
  "cours de russe en ligne",
  "russe pour enfants",
  "russe pour adultes",
  "préparation examen de russe",
  "école d'arabe",
  "académie d'arabe",
  "institut d'arabe",
  "centre d'arabe",
  "cours d'arabe",
  "cours particuliers d'arabe",
  "professeur d'arabe",
  "professeur particulier d'arabe",
  "tuteur d'arabe",
  "apprendre l'arabe",
  "étudier l'arabe",
  "cours de conversation en arabe",
  "cours d'arabe en ligne",
  "arabe pour enfants",
  "arabe pour adultes",
  "préparation examen d'arabe",
  "école de néerlandais",
  "académie de néerlandais",
  "institut de néerlandais",
  "centre de néerlandais",
  "cours de néerlandais",
  "cours particuliers de néerlandais",
  "professeur de néerlandais",
  "professeur particulier de néerlandais",
  "tuteur de néerlandais",
  "apprendre le néerlandais",
  "étudier le néerlandais",
  "cours de conversation en néerlandais",
  "cours de néerlandais en ligne",
  "néerlandais pour enfants",
  "néerlandais pour adultes",
  "préparation examen de néerlandais",
  "école de suédois",
  "académie de suédois",
  "institut de suédois",
  "centre de suédois",
  "cours de suédois",
  "cours particuliers de suédois",
  "professeur de suédois",
  "professeur particulier de suédois",
  "tuteur de suédois",
  "apprendre le suédois",
  "étudier le suédois",
  "cours de conversation en suédois",
  "cours de suédois en ligne",
  "suédois pour enfants",
  "suédois pour adultes",
  "préparation examen de suédois",
  "école de turc",
  "académie de turc",
  "institut de turc",
  "centre de turc",
  "cours de turc",
  "cours particuliers de turc",
  "professeur de turc",
  "professeur particulier de turc",
  "tuteur de turc",
  "apprendre le turc",
  "étudier le turc",
  "cours de conversation en turc",
  "cours de turc en ligne",
  "turc pour enfants",
  "turc pour adultes",
  "préparation examen de turc",
  "école de polonais",
  "académie de polonais",
  "institut de polonais",
  "centre de polonais",
  "cours de polonais",
  "cours particuliers de polonais",
  "professeur de polonais",
  "professeur particulier de polonais",
  "tuteur de polonais",
  "apprendre le polonais",
  "étudier le polonais",
  "cours de conversation en polonais",
  "cours de polonais en ligne",
  "polonais pour enfants",
  "polonais pour adultes",
  "préparation examen de polonais",
  "école d'hindi",
  "académie d'hindi",
  "institut d'hindi",
  "centre d'hindi",
  "cours d'hindi",
  "cours particuliers d'hindi",
  "professeur d'hindi",
  "professeur particulier d'hindi",
  "tuteur d'hindi",
  "apprendre l'hindi",
  "étudier l'hindi",
  "cours de conversation en hindi",
  "cours d'hindi en ligne",
  "hindi pour enfants",
  "hindi pour adultes",
  "préparation examen d'hindi",
  "école de vietnamien",
  "académie de vietnamien",
  "institut de vietnamien",
  "centre de vietnamien",
  "cours de vietnamien",
  "cours particuliers de vietnamien",
  "professeur de vietnamien",
  "professeur particulier de vietnamien",
  "tuteur de vietnamien",
  "apprendre le vietnamien",
  "étudier le vietnamien",
  "cours de conversation en vietnamien",
  "cours de vietnamien en ligne",
  "vietnamien pour enfants",
  "vietnamien pour adultes",
  "préparation examen de vietnamien",
  "école de langues",
  "académie de langues",
  "institut de langues",
  "centre de langues",
  "centre de formation",
  "centre d'apprentissage",
  "école de langues étrangères",
  "institut de formation",
  "centre éducatif",
  "académie",
  "institut",
  "centre de tutorat",
  "cours particuliers",
  "professeur particulier",
  "école privée",
  "académie privée",
  "préparation IELTS",
  "cours IELTS",
  "préparation TOEFL",
  "cours TOEFL",
  "préparation TOEIC",
  "préparation Cambridge",
  "préparation TOPIK",
  "cours TOPIK",
  "préparation JLPT",
  "cours JLPT",
  "préparation HSK",
  "cours HSK",
  "préparation DELE",
  "cours DELF",
  "cours DALF",
  "cours Goethe Zertifikat",
  "école bilingue",
  "école internationale",
  "école internationale de langues",
  "agence d'échange étudiant",
  "conseiller en études à l'étranger",
  "agence au pair",
  "service de traduction",
  "agence de traduction",
  "service d'interprétation",
  "agence d'interprètes",
  "centre culturel",
  "centre d'échange culturel",
  "éducation des adultes",
  "centre de formation continue",
  "formation linguistique en entreprise",
  "cours de langues pour entreprises",
  "services linguistiques",
  "école de langues pour enfants",
  "académie de langues pour enfants",
  "programme d'immersion linguistique",
  "centre d'échange conversationnel",
  "cours de langues de weekend",
  "cours de langues intensif",
  "programme de langues d'été",
  "centre de certification linguistique",
];