export const PT_TERMS = [
  "escola de coreano",
  "academia de coreano",
  "instituto de coreano",
  "centro de coreano",
  "curso de coreano",
  "cursos de coreano",
  "aulas de coreano",
  "aulas particulares de coreano",
  "professor de coreano",
  "professor particular de coreano",
  "tutor de coreano",
  "aprender coreano",
  "estudar coreano",
  "aulas de conversação de coreano",
  "aulas online de coreano",
  "aulas de coreano online",
  "coreano para crianças",
  "coreano para adultos",
  "preparação para exame de coreano",
  "escola de inglês",
  "academia de inglês",
  "instituto de inglês",
  "centro de inglês",
  "curso de inglês",
  "cursos de inglês",
  "aulas de inglês",
  "aulas particulares de inglês",
  "professor de inglês",
  "professor particular de inglês",
  "tutor de inglês",
  "aprender inglês",
  "estudar inglês",
  "aulas de conversação de inglês",
  "aulas online de inglês",
  "aulas de inglês online",
  "inglês para crianças",
  "inglês para adultos",
  "preparação para exame de inglês",
  "escola de espanhol",
  "academia de espanhol",
  "instituto de espanhol",
  "centro de espanhol",
  "curso de espanhol",
  "cursos de espanhol",
  "aulas de espanhol",
  "aulas particulares de espanhol",
  "professor de espanhol",
  "professor particular de espanhol",
  "tutor de espanhol",
  "aprender espanhol",
  "estudar espanhol",
  "aulas de conversação de espanhol",
  "aulas online de espanhol",
  "aulas de espanhol online",
  "espanhol para crianças",
  "espanhol para adultos",
  "preparação para exame de espanhol",
  "escola de francês",
  "academia de francês",
  "instituto de francês",
  "centro de francês",
  "curso de francês",
  "cursos de francês",
  "aulas de francês",
  "aulas particulares de francês",
  "professor de francês",
  "professor particular de francês",
  "tutor de francês",
  "aprender francês",
  "estudar francês",
  "aulas de conversação de francês",
  "aulas online de francês",
  "aulas de francês online",
  "francês para crianças",
  "francês para adultos",
  "preparação para exame de francês",
  "escola de português",
  "academia de português",
  "instituto de português",
  "centro de português",
  "curso de português",
  "cursos de português",
  "aulas de português",
  "aulas particulares de português",
  "professor de português",
  "professor particular de português",
  "tutor de português",
  "aprender português",
  "estudar português",
  "aulas de conversação de português",
  "aulas online de português",
  "aulas de português online",
  "português para crianças",
  "português para adultos",
  "preparação para exame de português",
  "escola de japonês",
  "academia de japonês",
  "instituto de japonês",
  "centro de japonês",
  "curso de japonês",
  "cursos de japonês",
  "aulas de japonês",
  "aulas particulares de japonês",
  "professor de japonês",
  "professor particular de japonês",
  "tutor de japonês",
  "aprender japonês",
  "estudar japonês",
  "aulas de conversação de japonês",
  "aulas online de japonês",
  "aulas de japonês online",
  "japonês para crianças",
  "japonês para adultos",
  "preparação para exame de japonês",
  "escola de chinês",
  "academia de chinês",
  "instituto de chinês",
  "centro de chinês",
  "curso de chinês",
  "cursos de chinês",
  "aulas de chinês",
  "aulas particulares de chinês",
  "professor de chinês",
  "professor particular de chinês",
  "tutor de chinês",
  "aprender chinês",
  "estudar chinês",
  "aulas de conversação de chinês",
  "aulas online de chinês",
  "aulas de chinês online",
  "chinês para crianças",
  "chinês para adultos",
  "preparação para exame de chinês",
  "escola de mandarim",
  "academia de mandarim",
  "instituto de mandarim",
  "centro de mandarim",
  "curso de mandarim",
  "cursos de mandarim",
  "aulas de mandarim",
  "aulas particulares de mandarim",
  "professor de mandarim",
  "professor particular de mandarim",
  "tutor de mandarim",
  "aprender mandarim",
  "estudar mandarim",
  "aulas de conversação de mandarim",
  "aulas online de mandarim",
  "aulas de mandarim online",
  "mandarim para crianças",
  "mandarim para adultos",
  "preparação para exame de mandarim",
  "escola de alemão",
  "academia de alemão",
  "instituto de alemão",
  "centro de alemão",
  "curso de alemão",
  "cursos de alemão",
  "aulas de alemão",
  "aulas particulares de alemão",
  "professor de alemão",
  "professor particular de alemão",
  "tutor de alemão",
  "aprender alemão",
  "estudar alemão",
  "aulas de conversação de alemão",
  "aulas online de alemão",
  "aulas de alemão online",
  "alemão para crianças",
  "alemão para adultos",
  "preparação para exame de alemão",
  "escola de italiano",
  "academia de italiano",
  "instituto de italiano",
  "centro de italiano",
  "curso de italiano",
  "cursos de italiano",
  "aulas de italiano",
  "aulas particulares de italiano",
  "professor de italiano",
  "professor particular de italiano",
  "tutor de italiano",
  "aprender italiano",
  "estudar italiano",
  "aulas de conversação de italiano",
  "aulas online de italiano",
  "aulas de italiano online",
  "italiano para crianças",
  "italiano para adultos",
  "preparação para exame de italiano",
  "escola de russo",
  "academia de russo",
  "instituto de russo",
  "centro de russo",
  "curso de russo",
  "cursos de russo",
  "aulas de russo",
  "aulas particulares de russo",
  "professor de russo",
  "professor particular de russo",
  "tutor de russo",
  "aprender russo",
  "estudar russo",
  "aulas de conversação de russo",
  "aulas online de russo",
  "aulas de russo online",
  "russo para crianças",
  "russo para adultos",
  "preparação para exame de russo",
  "escola de árabe",
  "academia de árabe",
  "instituto de árabe",
  "centro de árabe",
  "curso de árabe",
  "cursos de árabe",
  "aulas de árabe",
  "aulas particulares de árabe",
  "professor de árabe",
  "professor particular de árabe",
  "tutor de árabe",
  "aprender árabe",
  "estudar árabe",
  "aulas de conversação de árabe",
  "aulas online de árabe",
  "aulas de árabe online",
  "árabe para crianças",
  "árabe para adultos",
  "preparação para exame de árabe",
  "escola de holandês",
  "academia de holandês",
  "instituto de holandês",
  "centro de holandês",
  "curso de holandês",
  "cursos de holandês",
  "aulas de holandês",
  "aulas particulares de holandês",
  "professor de holandês",
  "professor particular de holandês",
  "tutor de holandês",
  "aprender holandês",
  "estudar holandês",
  "aulas de conversação de holandês",
  "aulas online de holandês",
  "aulas de holandês online",
  "holandês para crianças",
  "holandês para adultos",
  "preparação para exame de holandês",
  "escola de sueco",
  "academia de sueco",
  "instituto de sueco",
  "centro de sueco",
  "curso de sueco",
  "cursos de sueco",
  "aulas de sueco",
  "aulas particulares de sueco",
  "professor de sueco",
  "professor particular de sueco",
  "tutor de sueco",
  "aprender sueco",
  "estudar sueco",
  "aulas de conversação de sueco",
  "aulas online de sueco",
  "aulas de sueco online",
  "sueco para crianças",
  "sueco para adultos",
  "preparação para exame de sueco",
  "escola de turco",
  "academia de turco",
  "instituto de turco",
  "centro de turco",
  "curso de turco",
  "cursos de turco",
  "aulas de turco",
  "aulas particulares de turco",
  "professor de turco",
  "professor particular de turco",
  "tutor de turco",
  "aprender turco",
  "estudar turco",
  "aulas de conversação de turco",
  "aulas online de turco",
  "aulas de turco online",
  "turco para crianças",
  "turco para adultos",
  "preparação para exame de turco",
  "escola de polonês",
  "academia de polonês",
  "instituto de polonês",
  "centro de polonês",
  "curso de polonês",
  "cursos de polonês",
  "aulas de polonês",
  "aulas particulares de polonês",
  "professor de polonês",
  "professor particular de polonês",
  "tutor de polonês",
  "aprender polonês",
  "estudar polonês",
  "aulas de conversação de polonês",
  "aulas online de polonês",
  "aulas de polonês online",
  "polonês para crianças",
  "polonês para adultos",
  "preparação para exame de polonês",
  "escola de hindi",
  "academia de hindi",
  "instituto de hindi",
  "centro de hindi",
  "curso de hindi",
  "cursos de hindi",
  "aulas de hindi",
  "aulas particulares de hindi",
  "professor de hindi",
  "professor particular de hindi",
  "tutor de hindi",
  "aprender hindi",
  "estudar hindi",
  "aulas de conversação de hindi",
  "aulas online de hindi",
  "aulas de hindi online",
  "hindi para crianças",
  "hindi para adultos",
  "preparação para exame de hindi",
  "escola de vietnamita",
  "academia de vietnamita",
  "instituto de vietnamita",
  "centro de vietnamita",
  "curso de vietnamita",
  "cursos de vietnamita",
  "aulas de vietnamita",
  "aulas particulares de vietnamita",
  "professor de vietnamita",
  "professor particular de vietnamita",
  "tutor de vietnamita",
  "aprender vietnamita",
  "estudar vietnamita",
  "aulas de conversação de vietnamita",
  "aulas online de vietnamita",
  "aulas de vietnamita online",
  "vietnamita para crianças",
  "vietnamita para adultos",
  "preparação para exame de vietnamita",
  "escola de idiomas",
  "academia de idiomas",
  "instituto de idiomas",
  "centro de idiomas",
  "centro de línguas",
  "escola de línguas",
  "centro de formação",
  "centro de aprendizagem",
  "escola de idiomas estrangeiros",
  "centro educacional",
  "academia",
  "instituto",
  "centro de treinamento",
  "centro de tutoria",
  "aulas particulares",
  "professor particular",
  "escola particular",
  "academia particular",
  "curso IELTS",
  "preparação IELTS",
  "curso TOEFL",
  "preparação TOEFL",
  "curso TOEIC",
  "preparação Cambridge",
  "curso TOPIK",
  "preparação TOPIK",
  "curso JLPT",
  "preparação JLPT",
  "curso HSK",
  "preparação HSK",
  "curso DELE",
  "curso DELF",
  "curso DALF",
  "curso Goethe Zertifikat",
  "preparação exame de alemão",
  "exame CELPE-Bras",
  "preparação CELPE-Bras",
  "escola bilíngue",
  "escola internacional",
  "colégio internacional de idiomas",
  "agência de intercâmbio",
  "consultoria de intercâmbio estudantil",
  "agência de au pair",
  "serviço de tradução",
  "agência de tradução",
  "serviço de interpretação",
  "agência de intérpretes",
  "centro cultural",
  "centro de intercâmbio cultural",
  "educação para adultos",
  "centro de educação continuada",
  "treinamento de idiomas para empresas",
  "aulas de idiomas para empresas",
  "serviços linguísticos",
  "escola de idiomas para crianças",
  "academia de idiomas infantil",
  "programa de imersão linguística",
  "centro de intercâmbio de conversação",
  "curso de idiomas de fim de semana",
  "curso intensivo de idiomas",
  "programa de idiomas de verão",
  "centro de certificação de idiomas",
];